language: rust
rust:
  - stable
  - beta
  - nightly
os: linux
dist: trusty
sudo: required
env: TYPE=default RUST_BACKTRACE=1
cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target/debug
  - $TRAVIS_BUILD_DIR/target/release
  - $TRAVIS_BUILD_DIR/target/benchcmp/target
  - $TRAVIS_BUILD_DIR/fuzz/target
  - $TRAVIS_BUILD_DIR/fuzz/corpus
script:
- cargo build --verbose
- cargo build --verbose --release
- cargo test --verbose
- cargo test --verbose --release
matrix:
  include:
    - os: linux
      rust: stable
      env: TYPE=rustfmt RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f rustfmt || exit 0)
        - cargo fmt -- --write-mode=diff
    - os: linux
      rust: nightly
      env: TYPE=clippy RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f clippy || exit 0)
        - cargo clippy
    - os: linux
      rust: nightly
      env: TYPE=fuzz_webhook_create RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f cargo-fuzz || exit 0)
        - sudo -E $HOME/.cargo/bin/cargo fuzz run -s address fuzz_webhook_create -- -max_total_time=300
        - sudo chown -R travis $HOME/.cargo
    - os: linux
      rust: nightly
      env: TYPE=fuzz_webhook_pull_request RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f cargo-fuzz || exit 0)
        - sudo -E $HOME/.cargo/bin/cargo fuzz run -s address fuzz_webhook_pull_request -- -max_total_time=300
        - sudo chown -R travis $HOME/.cargo
    - os: linux
      rust: nightly
      env: TYPE=fuzz_webhook_push RUST_BACKTRACE=1
      script:
        - (travis_wait 20 cargo install -f cargo-fuzz || exit 0)
        - sudo -E $HOME/.cargo/bin/cargo fuzz run -s address fuzz_webhook_push -- -max_total_time=300
        - sudo chown -R travis $HOME/.cargo
